name: My Target Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Parse and use payload
        run: |
          echo "Service: ${{ github.event.client_payload.service }}"
          echo "Version: ${{ github.event.client_payload.version }}"
          echo "Unit tests: ${{ github.event.client_payload.unit }}"
          echo "Integration tests: ${{ github.event.client_payload.integration }}"